### ISSUE TITLE
doesn't compile

### ISSUE THREAD

**Issue by xiaoruiDu** [lsds/LightSaber#1]
Hey, thanks for the great work.  

I am reading your code and would like to try the SG1 query with the source dataset you provide.

Here are some issues I got:

- the project is not compiling as you are using NUMACircularQueryBuffer.h in real but you put NumaCircularQueryBuffer.h in your cmakelist. 

- the provided docker env still can't compile LightSaber (after fixing the above issue).

It would be great if you can quickly check the project. 

Looking forward your reply

Xiaorui

**Comment by grtheod** [comment]
Hi Xiaorui,

I am not sure I can reproduce your issue with the information you provided. The Docker file was functional the last time I checked it on my laptop.

What's the setup environment? What's the error?

The code was written a couple of years ago (Ubuntu 18.04.5 LTS) and probably doesn't run as it does in newer versions (or Mac).

Cheers,
George

**Comment by xiaoruiDu** [comment]
Hey George,

Thanks for the reply. 

I get the following errors when I run the ```./smartgrid``` binary in docker:
```
error: unknown argument: '-internal-isystem'
error: -emit-llvm cannot be used when linking
```

By the way, Do you still have your dataset somewhere accessible? (i.e., Smart grid dataset and Cluster Monitoring) it would be very nice if you could share it as the official link is closed now.

Thanks again for the reply,
Have a nice day.
Xiaorui.

**Comment by grtheod** [comment]
Hi Xiaorui,

Unfortunately, I don't have access to a linux machine and can't reproduce the issue. 

As for the datasets, you can download them from the following links: i) https://github.com/google/cluster-data/blob/master/ClusterData2011_2.md ; ii) http://www.doc.ic.ac.uk/~mweidlic/sorted.csv.gz (found it here https://blog.yomo.run/posts/debs2014-grand-challenge-by-yomo)

Cheers,
George

**Comment by xiaoruiDu** [comment]
Hey Geoge,

Thanks for the fast reply and references!

I think we can close this issue.

B.S.
Xiaorui
